# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Abluestar
tagline:          'this is the tag line'
description:      'Projects of Steven Smethurst'
url:              http://funvill.github.io

author:
  name:           'funvill'
  url:            

paginate:         10

# Custom vars
version:          1.0

github:           
  repo:           https://github.com/funvill/funvill.github.io

