# Dependencies
markdown:         kramdown
highlighter:      rouge 

# Permalinks
permalink:        /:title

# Setup
title:            ABlueStar
tagline:          'I make things, sometimes they are awesome things'
description:      'Steven Smethurst is a Vancouver based <em>Maker</em>, <em>Hacker</em>, <em>Coder</em>, and all around <em>great guy!</em>'
url:              http://funvill.github.io

author:
  name:           'funvill'
  url:            http://blog.abluestar.com

paginate:         1

collections:
  project
    output: true
    permalink: /p/:path/
    path: _projects

# Custom vars
version:          1.0

github:           
  repo:           https://github.com/funvill/funvill.github.io

prose:
  media:          'public/uploads'
  
