# Dependencies
markdown:         kramdown
highlighter:      rouge 

# Permalinks
permalink:        /:title

# Setup
title:            ABlueStar
tagline:          'I make things, sometimes they are awesome things'
description:      'Steven Smethurst is a Vancouver based <em>Maker</em>, <em>Hacker</em>, <em>Coder</em>, <em>Artist</em>, and all around <em>great guy!</em>'
url:              https://blog.abluestar.com
enforce_ssl:      blog.abluestar.com


author:
  name:           'funvill'
  url:            https://blog.abluestar.com

paginate:         1

# Custom vars
version:          1.0

github:           
  repo:           https://github.com/funvill/funvill.github.io

prose:
  media:          'public/uploads'
  
twitter:
  username:       funvill

gems:
  - jekyll-sitemap